config/routes.rb
TeamGenerator::Application.routes.draw do

  root to: "welcome#index"

  post "/teams/randomize"

  get "/teams/num_teams"

  delete "/students/delete_all"
  delete "/teams/delete_all"

  resources :teams 

  resources :students

end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render action: 'show', status: :created, location: @student }
      else
        format.html { render action: 'new' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end
  # DELETE /students/1
  # DELETE /students/1.json
  def delete_all
    Student.delete_all

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :email, :github_username)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  include TeamsHelper

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  def num_teams
  end

  def randomize

    #render :text => params[:num]


    # calling a "helper method" in the helpers folder (/app/helpers/teams_helper)
    # this is a good way of getting "worker" code out of the controller
    create_teams
  end




  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render action: 'show', status: :created, location: @team }
      else
        format.html { render action: 'new' }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url }
      format.json { head :no_content }
    end
  end

   # DELETE /students/1
  # DELETE /students/1.json
  def delete_all
    Team.delete_all

    respond_to do |format|
      format.html { redirect_to teams_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:student_id, :is_leader, :team_id)
    end

   
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper

	def create_teams
		# this tells us how many teams we want
	    @num_teams = params[:num]

	    # now get all the students. divide the num of students by the num of teams
	    @students = Student.all

	    # create an array of student ids
	    student_arr = Array.new

	    @students.each do |student|
	      student_arr.push(student.id)
	    end

	    # how many students per team? is there a remainder
	    students_per_team = @students.length.to_i / @num_teams.to_i

	    # create an array of team ids depending on many teams we have
	    team_arr = Array.new

	    for i in 1..@num_teams.to_i
	      team_arr.push(i)
	    end

	    # now that we have an array that contains our students, and an array that contains our teams, 
	    # we need to go back and loop through the students one more time and start assigning them to 
	    # teams. we will need a new HASH that will tell us if each team has enough students
	    # if a team has enough students, we won't add to that team
	    
	    #**********************
	    # note: code below here is untested and unfinished

	    #**********************

	    hash_counter = create_empty_hash @num_teams

		studentsstr = ''
	    team_arr.each do |team_num|

	    	for i in 1..students_per_team
	    		rand_num = rand(student_arr.length)

	    		student_id = student_arr[rand_num]

	    		studentsstr = student_id.to_s + ', ' + studentsstr

	    		# remove this from the student array so it's not used again
	    		student_arr.delete(rand_num)
	    		puts "array!"
	    		puts student_arr
	    	end
	    	
	    	# increment our team counter by 1. when we're at or above, the quota
	    	# we'll break out of this loop

	    end
	    
	    render :text => studentsstr
	end
	def create_empty_hash num_teams
      empty_hash = Hash.new


      for i in 1..@num_teams.to_i
        empty_hash[i] = 0
      end
     
      empty_hash
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeamGenerator</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h3>Team Generator</h3>
<%= link_to 'STUDENTS', students_path %> |
<%= link_to 'TEAMS', teams_path %> |
<%= link_to 'TEAM SET-UP', teams_num_teams_path %> 
<br><br>
<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :github_username %><br>
    <%= f.text_field :github_username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Github username</th>
      <th></th>
      <th></th>
      <th></th>

    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.email %></td>
        <td><%= student.github_username %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>
<%= link_to 'Remove all students', students_delete_all_path, method: :delete, data: { confirm: 'Are you like totally sure you wanna delete ALL students?' } %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Github username:</strong>
  <%= @student.github_username %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/welcome/index.html.erb
<h1><center>Team Generator!</center></h1>
<br><br><br>
<p>TJ's super fancy random team generator</p>